### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ducpro0211kk** [vic1707/AutoPlay-PokeMeow-Discord#13]
It's 16:27:50, working time !
Traceback (most recent call last):
  File "bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 65, in __init__
    webdriver.Edge.__init__(self, options)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 56, in __init__
    self.edge_service.start()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1247, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 549, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38\lib\os.py", line 816, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not Options

Press Enter to close !!
How can I fix it?

**Comment by vic1707** [comment]
I have to admit I never tested it with Edge (don't have any Windows computer).

It seems that I don't pass the good arguments on `CustomDriver.py, line 65`, which seems due to Edge using chromium ?

**Comment by vic1707** [comment]
Just commited  184a0f5 which I hope will fit it.

I'll try it on a Windows computer asap.

If you can try it before me it would be great ^^(don't forget to reuse the `python -m pip install -r requirments.txt` since the update need a new package).

**Comment by ducpro0211kk** [comment]
> Just commited [184a0f5](https://github.com/vic1707/AutoPlay-PokeMeow-Discord/commit/184a0f5a3af7840359dc68b90db359a65fee0b56) which I hope will fit it.
> 
> I'll try it on a Windows computer asap.
> 
> If you can try it before me it would be great ^^(don't forget to reuse the `python -m pip install -r requirments.txt` since the update need a new package).

File "bot.py", line 11, in <module>
    from Classes.CustomDriver import CustomDriver
  File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 11, in <module>
    from msedge.selenium_tools import EdgeOptions
ModuleNotFoundError: No module named 'msedge'
after i change it it looks like this

**Comment by vic1707** [comment]
> > Just commited [184a0f5](https://github.com/vic1707/AutoPlay-PokeMeow-Discord/commit/184a0f5a3af7840359dc68b90db359a65fee0b56) which I hope will fit it.
> > I'll try it on a Windows computer asap.
> > If you can try it before me it would be great ^^(don't forget to reuse the `python -m pip install -r requirments.txt` since the update need a new package).
> 
> File "bot.py", line 11, in
> from Classes.CustomDriver import CustomDriver
> File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 11, in
> from msedge.selenium_tools import EdgeOptions
> ModuleNotFoundError: No module named 'msedge'
> after i change it it looks like this

have you re-run the `python -m pip install -r requirments.txt` command to install the `msedge` module ?

**Comment by ducpro0211kk** [comment]
> python -m pip install -r requirments.txt

yes, i ran it again

**Comment by vic1707** [comment]
> > python -m pip install -r requirments.txt
> 
> yes, i ran it again

Crap that was my fault, the package to install is `msedge-selenium-tools` not `msedge`, I modified it again, can you try ?

**Comment by ducpro0211kk** [comment]
> > > python -m pip install -r requirments.txt
> > 
> > 
> > yes, i ran it again
> 
> Crap that was my fault, the package to install is `msedge-selenium-tools` not `msedge`, I modified it again, can you try ?

 File "bot.py", line 11, in <module>
    from Classes.CustomDriver import CustomDriver
  File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 11, in <module>
    from msedge.selenium.tools import EdgeOptions
ModuleNotFoundError: No module named 'msedge'
now it's another error

**Comment by ducpro0211kk** [comment]
File "bot.py", line 11, in <module>
    from Classes.CustomDriver import CustomDriver
  File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 11
    from msedge-selenium-tools import EdgeOptions
               ^
SyntaxError: invalid syntax

oh sorry I sent the wrong one

**Comment by vic1707** [comment]
> File "bot.py", line 11, in
> from Classes.CustomDriver import CustomDriver
> File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 11
> from msedge-selenium-tools import EdgeOptions
> ^
> SyntaxError: invalid syntax
> 
> oh sorry I sent the wrong one

I think you didn't cloned the repo again (which I understand for such small changes).
The line ` from msedge-selenium-tools import EdgeOptions`
Should be ` from msedge.selenium_tools import EdgeOptions`
The current version load completly on my Linux machine (can't test Edge) but I can certify that there is no syntax error.

**Comment by ducpro0211kk** [comment]
File "bot.py", line 11, in <module>
    from Classes.CustomDriver import CustomDriver
  File "C:\Users\Admin\Downloads\AutoPlay-PokeMeow-Discord-main\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 11, in <module>
    from msedge.selenium_tools import EdgeOptions
ModuleNotFoundError: No module named 'msedge'

**Comment by vic1707** [comment]
the module hasn't been installed, did you re-run the install command after the last update ?

**Comment by vic1707** [comment]
the requirments.txt file has changed

**Comment by ja-den** [comment]
I get this same issue even after your update

**Comment by vic1707** [comment]
> I get this same issue even after your update

Did you re-run the install command?

**Comment by ja-den** [comment]
> > I get this same issue even after your update
> 
> Did you re-run the install command?

Yes, this is what it says

C:\Users\jaden\Desktop\AutoPlay-PokeMeow-Discord-main>python -m pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyotp==2.4.1 in c:\users\jaden\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 4)) (2.4.1)
Requirement already satisfied: selenium==3.141.0 in c:\users\jaden\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 7)) (3.141.0)
Requirement already satisfied: msedge-selenium-tools in c:\users\jaden\appdata\roaming\python\python38\site-packages (from -r requirements.txt (line 9)) (3.141.3)
Requirement already satisfied: urllib3 in c:\users\jaden\appdata\roaming\python\python38\site-packages (from selenium==3.141.0->-r requirements.txt (line 7)) (1.26.6)

**Comment by vic1707** [comment]
so you still have the module not found even after redownloading the code and intalling everything...

Strange. For now I don't have any solution because I can't test the code myself...

**Comment by vic1707** [comment]
last commit fixes the loading of edge a7cd207, unfortunately I wasn't able to restore headless mode atm. Hope I'll find a solution soon.
Not proud of it but at least it runs...
