### ISSUE TITLE
Script not running

### ISSUE THREAD

**Issue by adriansenpai** [vic1707/AutoPlay-PokeMeow-Discord#15]
It's 22:53:12, working time !
[2280:8996:0712/225313.234:ERROR:storage_reserve.cc(164)] Failed to open file to mark as storage reserve: C:\Users\KEIDOR~1\AppData\Local\Temp\scoped_dir7704_2110748713\Default\Code Cache\js

DevTools listening on ws://127.0.0.1:64436/devtools/browser/cd89f332-283d-4d86-a3d0-d6708ac5fc85
[2280:4864:0712/225313.546:ERROR:edge_auth_errors.cc(383)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:

[2280:4864:0712/225313.767:ERROR:device_event_log_impl.cc(214)] [22:53:13.767] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[2280:4864:0712/225313.773:ERROR:device_event_log_impl.cc(214)] [22:53:13.773] USB: usb_device_handle_win.cc:1058 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[2280:4864:0712/225314.157:ERROR:profile_manager.cc(990)] Cannot create profile at path C:\Users\Keidorian\AppData\Local\Microsoft\Edge\User Data\Default
[2280:4864:0712/225314.164:ERROR:profile_manager.cc(1963)] Cannot create profile at path C:\Users\Keidorian\AppData\Local\Microsoft\Edge\User Data\Default
[2280:4864:0712/225325.733:ERROR:CONSOLE(1)] "PSL: window.chrome.ntpSettingsPrivate.getPref does not have campaigns. [object Object] Mon Jul 12 2021 22:53:25 GMT+0800 (Philippine Standard Time)", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/vendors.fb0d14a53ce138fb6c4f.js (1)
[2280:4864:0712/225326.086:ERROR:CONSOLE(1304)] "Uncaught (in promise) undefined", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/common.9ca9af66d8a5623cf124.js (1304)
[2280:4864:0712/225333.432:ERROR:CONSOLE(1)] "Request has failed. [object Object] Mon Jul 12 2021 22:53:33 GMT+0800 (Philippine Standard Time)", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/vendors.fb0d14a53ce138fb6c4f.js (1)
[2280:4864:0712/225333.432:ERROR:CONSOLE(1)] " [object Object] Mon Jul 12 2021 22:53:33 GMT+0800 (Philippine Standard Time)", source: https://assets.msn.com/bundles/v1/edgeChromium/latest/vendors.fb0d14a53ce138fb6c4f.js (1)
Traceback (most recent call last):
  File "D:\dl\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 105, in FindMessages
    return WebDriverWait(self, timeout=timeout).until(lambda driver: driver.find_elements_by_xpath(self.MSG_XPATH))[::-1]
  File "C:\Users\Keidorian\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dl\AutoPlay-PokeMeow-Discord-main\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "D:\dl\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 74, in __init__
    self.LAST_MSG = self.FindMessages('find last message')[0]
  File "D:\dl\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 106, in FindMessages
    except TimeoutException: raise Exception(f'"{ item }" took too much time to apear, dev can\'t really do anything to fix it')
Exception: "find last message" took too much time to apear, dev can't really do anything to fix it

Press Enter to close !!

**Comment by vic1707** [comment]
Can I have some details on what happened instead of just a sample of error meesage ?
Did Edge openned  ? did it go to the channel, login , send a command ? 

As I can see on the last line of the error msg `Exception: "find last message" took too much time to apear, dev can't really do anything to fix it`.

**Comment by Gallente-venture** [comment]
I think I had the same kind of issue, Firefox opened, it successfully logged in, and went to the correct channel but it could not send the first command of checklist.

**Comment by vic1707** [comment]
Can I bet that there isn't any message in the channel? Try sending any kind of message in the channel then reloading the bot.
I got the issue yesterday, I'll have to edit the README to tell that at least 1 message is required in the channel

**Comment by Gallente-venture** [comment]
I think I had a few messages in there before. and what is weird is that the bot with the same format works on a different account.

**Comment by vic1707** [comment]
> I think I had a few messages in there before. and what is weird is that the bot with the same format works on a different account.

You said same kind of issue, the issue here might be related to not having messages.
For you, do you have an error message (if yes open a new issue)?
To debug your issue try first running it without the headless flasg

**Comment by vic1707** [comment]
No news
