### ISSUE TITLE
Timeout error, nothing sent

### ISSUE THREAD

**Issue by dreir2** [vic1707/AutoPlay-PokeMeow-Discord#36]
I'm having this issue where it open up firefox and login to the right channel but nothing was entered in the typing space. Here is the cmd error. Thank you for your help

Traceback (most recent call last):
  File "C:\Users\dreir\poke\Classes\CustomDriver.py", line 100, in FindOneByXPATH
    return WebDriverWait(self, timeout=timeout).until(EC.element_to_be_clickable((By.XPATH, PATH)))
  File "C:\Users\dreir\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dreir\poke\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\dreir\poke\Classes\CustomDriver.py", line 74, in __init__
    self.SEND_MSG_BAR = self.FindOneByXPATH(self.SEND_MSG_BAR_XPATH, 'Discord sending bar')
  File "C:\Users\dreir\poke\Classes\CustomDriver.py", line 101, in FindOneByXPATH
    except TimeoutException: raise Exception(f'"{ item }" took too much time to apear, dev can\'t really do anything to fix it')
Exception: "Discord sending bar" took too much time to apear, dev can't really do anything to fix it

**Comment by vic1707** [comment]
> `Exception: "Discord sending bar" took too much time to apear, dev can't really do anything to fix it`

The last line is self explainatory... Did you try running the bot without the `-H` flag to see what the driver windows shows?

**Comment by dreir2** [comment]
I'm not sure what u mean by -H flag. If you mean running in headless mode I do not run with that

**Comment by vic1707** [comment]
Yes I meant that.
But only giving me this kind of answer won't  help me solve your issue, that's why I created the issue template that you're not following! reread it and give the infos i need please.

**Comment by dreir2** [comment]
Bug: It opens up discord, log in with user and password, enter the right channel and does nothing. command prompt shows timeout.

Screenshot of discord:
![image](https://user-images.githubusercontent.com/96963811/149152869-639f49a9-91be-49da-9015-53e2a952c0ec.png)


geckodriver log: (not sure if this is useful)
###!!! [Child][MessageChannel] Error: (msgtype=0x390147,name=PContent::Msg_ScriptError) Channel closing: too late to send/recv, messages will be lost


###!!! [Child][MessageChannel] Error: (msgtype=0xAA0006,name=PWebSocket::Msg_DeleteSelf) Channel closing: too late to send/recv, messages will be lost

1641983921347	geckodriver	INFO	Listening on 127.0.0.1:49818
1641983924369	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\dreir\\AppData\\Local\\Temp\\rust_mozprofileUJRlr3"
1641983925294	Marionette	INFO	Marionette enabled
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\dreir\\AppData\\Local\\Temp\\rust_mozprofileUJRlr3\\search.json.mozlz4", (void 0)))
1641983928827	Marionette	INFO	Listening on port 49831
1641983928985	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
JavaScript warning: https://discord.com/assets/0b59a87b26a13b7583bf.js, line 3620: unreachable code after return statement
JavaScript warning: https://discord.com/assets/0b59a87b26a13b7583bf.js, line 3620: unreachable code after return statement
JavaScript error: resource://gre/actors/AutoCompleteChild.jsm, line 125: Error: Invalid autocomplete selectedIndex
JavaScript error: resource://gre/actors/AutoCompleteChild.jsm, line 125: Error: Invalid autocomplete selectedIndex
JavaScript error: resource://gre/modules/LoginManagerChild.jsm, line 194: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 125}]'[JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 125}]' when calling method: [nsIAutoCompletePopup::selectedIndex]
1641984064658	Marionette	INFO	Stopped listening on port 49831
console.warn: TopSitesFeed: Failed to fetch data from Contile server: NetworkError when attempting to fetch resource.

###!!! [Parent][MessageChannel] Error: (msgtype=0x39007A,name=PContent::Msg_DestroyBrowsingContextGroup) Closed channel: cannot send/recv


###!!! [Child][MessageChannel] Error: (msgtype=0x390147,name=PContent::Msg_ScriptError) Channel closing: too late to send/recv, messages will be lost


###!!! [Child][MessageChannel] Error: (msgtype=0xAA0006,name=PWebSocket::Msg_DeleteSelf) Channel closing: too late to send/recv, messages will be lost

jHQb\\search.json.mozlz4", (void 0)))
1641984053823	Marionette	INFO	Listening on port 50013
1641984054004	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
JavaScript warning: https://discord.com/assets/0b59a87b26a13b7583bf.js, line 3620: unreachable code after return statement
JavaScript warning: https://discord.com/assets/0b59a87b26a13b7583bf.js, line 3620: unreachable code after return statement
JavaScript error: resource://gre/actors/AutoCompleteChild.jsm, line 125: Error: Invalid autocomplete selectedIndex
JavaScript error: resource://gre/actors/AutoCompleteChild.jsm, line 125: Error: Invalid autocomplete selectedIndex
JavaScript error: resource://gre/modules/LoginManagerChild.jsm, line 194: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 125}]'[JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 125}]' when calling method: [nsIAutoCompletePopup::selectedIndex]
JavaScript error: , line 0: NS_ERROR_NOT_AVAILABLE
1:50070
1641984100291	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "-headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\dreir\\AppData\\Local\\Temp\\rust_mozprofileAM0sB5"
*** You are running in headless mode.
1641984100575	Marionette	INFO	Marionette enabled
[GFX1-]: RenderCompositorSWGL failed mapping default framebuffer, no dt
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\dreir\\AppData\\Local\\Temp\\rust_mozprofileAM0sB5\\search.json.mozlz4", (void 0)))
1641984101472	Marionette	INFO	Listening on port 50078
1641984101824	RemoteAgent	WARN	TLS certificate errors will be ignored for this session
JavaScript warning: https://discord.com/assets/0b59a87b26a13b7583bf.js, line 3620: unreachable code after return statement
JavaScript warning: https://discord.com/assets/0b59a87b26a13b7583bf.js, line 3620: unreachable code after return statement
JavaScript error: resource://gre/actors/AutoCompleteChild.jsm, line 125: Error: Invalid autocomplete selectedIndex
JavaScript error: resource://gre/actors/AutoCompleteChild.jsm, line 125: Error: Invalid autocomplete selectedIndex
JavaScript error: resource://gre/modules/LoginManagerChild.jsm, line 194: NS_ERROR_XPC_JAVASCRIPT_ERROR_WITH_DETAILS: [JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 125}]'[JavaScript Error: "Invalid autocomplete selectedIndex" {file: "resource://gre/actors/AutoCompleteChild.jsm" line: 125}]' when calling method: [nsIAutoCompletePopup::selectedIndex]
JavaScript error: , line 0: NS_ERROR_NOT_AVAILABLE

OS:
Edition	Windows 10 Home
Version	20H2
Installed on	‎3/‎08/‎2021
OS build	19042.1110
Experience	Windows Feature Experience Pack 120.2212.3530.0

Browser:
Firefox

Additional context:
It was actually working fine for the past few days until I got banned for 36hrs. Once unban, I played normally for a few hours before using the bot and it no longer works. Tried running in headless mode incase it works as I was not in headless mode orginally.

**Comment by dreir2** [comment]
It is still not working even removing the pop-up. It used to work even with the popup as well. I tried redownloading the files and placing them in a different drive but it still does not work.
