### ISSUE TITLE
ModuleNotFoundError: No module named 'pyotp'

### ISSUE THREAD

**Issue by BloodGodMoon** [vic1707/AutoPlay-PokeMeow-Discord#37]
Classes\CustomDriver.py", line 5, in <module>
    from pyotp import TOTP
ModuleNotFoundError: No module named 'pyotp'

**Comment by vic1707** [comment]
did you even read the README, guess no since you didn't even used the issue template ? 
pyotp isn't by default on your computer you need to install it...

`python -m pip install -r requirements.txt` Windows
or
`python3 -m pip install -r requirements.txt` MAC/Linux

**Comment by BloodGodMoon** [comment]
sorry,my english actually no good at all and i dont understand where i need to type python -m pip install -r requirements.txt

**Comment by BloodGodMoon** [comment]
type in the cmd or where?

**Comment by BloodGodMoon** [comment]
i type in cmd and i get                        python.exe: No module named pip

**Comment by vic1707** [comment]
not having a good english isn't really an excuse for not reading a README...
mine isn't perfect neither (french)

then you have to install pip https://phoenixnap.com/kb/install-pip-windows

**Comment by BloodGodMoon** [comment]
ok...... but at the last when i type pyhon bot.py  -u.............and i get It's 18:37:44, working time !
Traceback (most recent call last):
  File "C:\Users\wongj\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\wongj\Classes\CustomDriver.py", line 49, in __init__
    webdriver.Firefox.__init__(self, executable_path=path_binary, options=options)
  File "D:\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "D:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "D:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line

**Comment by BloodGodMoon** [comment]
at the last i get this

**Comment by BloodGodMoon** [comment]
Is that complete?

**Comment by vic1707** [comment]
do you have firefox on your computer? did you download every file i provided?

**Comment by BloodGodMoon** [comment]
I use opera....., i change fire fox

**Comment by vic1707** [comment]
you really didn't read the readme...
firefox is used by default and requires to be installed on your computer,
if you want to use opera you'll have to add `-D Opera` at the end of the python command

**Comment by BloodGodMoon** [comment]
i read already and i also change the -D to opera already but not work so i change fire fox now

**Comment by BloodGodMoon** [comment]
It's 23:05:57, working time !
Traceback (most recent call last):
  File "C:\Users\wongj\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\wongj\Classes\CustomDriver.py", line 72, in __init__
    self.DiscordLogin(self.CHANNEL)
  File "C:\Users\wongj\Classes\CustomDriver.py", line 77, in DiscordLogin
    self.get(CHANNEL)
  File "D:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "D:\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: URL constructor: 'XXXXXXX' is not a valid URL.

**Comment by BloodGodMoon** [comment]
i can confirm the link is same and right

**Comment by BloodGodMoon** [comment]
but why still cannot

**Comment by BloodGodMoon** [comment]
oh,i know whats wrong,dont write the link in the quotes

**Comment by vic1707** [comment]
can you send the full command you used? (hide your email and password the rest can be raw)

**Comment by BloodGodMoon** [comment]
python bot.py -U 'JY' -M '-------' -P '------' -C -------

**Comment by BloodGodMoon** [comment]
but know i clear the quotes

**Comment by vic1707** [comment]
the channel should be in quotes (as well as every parameter) and containing "https://discord ......" (which is why I told discord link can be raw : wanted to see if you've only set the IDs)

**Comment by BloodGodMoon** [comment]
know already can open until into the discord but.....

**Comment by BloodGodMoon** [comment]
It's 23:20:56, working time !
Traceback (most recent call last):
  File "C:\Users\wongj\Classes\CustomDriver.py", line 99, in FindOneByXPATH
    return WebDriverWait(self, timeout=timeout).until(EC.element_to_be_clickable((By.XPATH, PATH)))
  File "D:\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wongj\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\wongj\Classes\CustomDriver.py", line 73, in __init__
    self.SEND_MSG_BAR = self.FindOneByXPATH(self.SEND_MSG_BAR_XPATH, 'Discord sending bar')
  File "C:\Users\wongj\Classes\CustomDriver.py", line 100, in FindOneByXPATH
    except TimeoutException: raise Exception(f'"{ item }" took too much time to apear, dev can\'t really do anything to fix it')
Exception: "Discord sending bar" took too much time to apear, dev can't really do anything to fix it

**Comment by vic1707** [comment]
`Exception: "Discord sending bar" took too much time to apear, dev can't really do anything to fix it`
I love when people just send error messages without any other infos, you understand that you're only making my life difficult by doing so?
What whas displayed on the browser window before the crash ? did it go through the login page? is there a pop-up or something?

**Comment by BloodGodMoon** [comment]
it can login and go to the right channel but stop at there and no any pop up so i go to take a look at CMD and it shows me that..........

**Comment by vic1707** [comment]
> but stop
immediately? after some time?

**Comment by BloodGodMoon** [comment]
it just login and go to the right channel and stop at there and do not do anything else

**Comment by vic1707** [comment]
so it wait some time before crashing right?

**Comment by BloodGodMoon** [comment]
no crashing

**Comment by vic1707** [comment]
wait, never? no crashes at all ? the browser window never crashes?

**Comment by BloodGodMoon** [comment]
yes

**Comment by BloodGodMoon** [comment]
just stop at the channel

**Comment by BloodGodMoon** [comment]
it auto open discord and auto login and auto go to the channel that i want and just stop at there,the browser no close and no crash

**Comment by vic1707** [comment]
i updated the script try with the new version

**Comment by BloodGodMoon** [comment]
![image_2022-03-24_233918](https://user-images.githubusercontent.com/88900524/159954121-28296d9c-0589-489d-a249-d6eb13bb348a.png)

**Comment by BloodGodMoon** [comment]
it  stop at here and then the CMD show me that thing that just now i send

**Comment by BloodGodMoon** [comment]
ok,i try the new script

**Comment by BloodGodMoon** [comment]
It's 23:48:58, working time !
Traceback (most recent call last):
  File "C:\Users\wongj\Classes\CustomDriver.py", line 105, in FindMessages
    return WebDriverWait(self, timeout=timeout).until(lambda driver: driver.find_elements_by_xpath(self.MSG_XPATH))[::-1]
  File "D:\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\wongj\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\wongj\Classes\CustomDriver.py", line 74, in __init__
    self.LAST_MSG = self.FindMessages('find last message')[0]
  File "C:\Users\wongj\Classes\CustomDriver.py", line 106, in FindMessages
    except TimeoutException: raise Exception(f'"{ item }" took too much time to apear, dev can\'t really do anything to fix it')
Exception: "find last message" took too much time to apear, dev can't really do anything to fix it

**Comment by vic1707** [comment]
and? do you remember what i said about just getting an error message?
"doc it hurts" this is as helpfull as this

**Comment by vic1707** [comment]
script updated which should fix the error, 
be warned next error if you only give an error message I'll close the issue without answering

**Comment by BloodGodMoon** [comment]
sorry.......same eror...........just stop at the channel only.......

**Comment by BloodGodMoon** [comment]
so how can i fix it.........

**Comment by vic1707** [comment]
new update but can't be sure if it'll work

**Comment by BloodGodMoon** [comment]
Ok

**Comment by BloodGodMoon** [comment]
I will try

**Comment by vic1707** [comment]
So, did it work ?

**Comment by BloodGodMoon** [comment]
no....same error again.....

**Comment by BloodGodMoon** [comment]
and i try to change another browser but not work it still auto open fire fox

**Comment by vic1707** [comment]
that's due to the new discord version, classes have changed in the HTML code of the page, I need to find the right one

**Comment by BloodGodMoon** [comment]
errr if you uptaded can you notice me in discord JY#6265 ?

**Comment by slender2kz** [comment]
> errr if you uptaded can you notice me in discord JY#6265 ?

accept my request, i have some questions if you got it to work.
