### ISSUE TITLE
customdriver issue and timeout issue even in headless mode :/

### ISSUE THREAD

**Issue by na0sis111** [vic1707/AutoPlay-PokeMeow-Discord#38]
hello so my cmd say that after a couple minute a launch the bot :/

Traceback (most recent call last):
  File "D:\divers\Nouveau_dossier\pkmeow\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 99, in FindOneByXPATH
    return WebDriverWait(self, timeout=timeout).until(EC.element_to_be_clickable((By.XPATH, PATH)))
  File "C:\Users\naosi\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\divers\Nouveau_dossier\pkmeow\AutoPlay-PokeMeow-Discord-main\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "D:\divers\Nouveau_dossier\pkmeow\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 73, in __init__
    self.SEND_MSG_BAR = self.FindOneByXPATH(self.SEND_MSG_BAR_XPATH, 'Discord sending bar')
  File "D:\divers\Nouveau_dossier\pkmeow\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 100, in FindOneByXPATH
    except TimeoutException: raise Exception(f'"{ item }" took too much time to apear, dev can\'t really do anything to fix it')
Exception: "Discord sending bar" took too much time to apear, dev can't really do anything to fix it

**Comment by vic1707** [comment]
As the error says, the bot can't find the area where to type, it's working minutes before crash?

**Comment by na0sis111** [comment]
it just open firefox, log into discord go to the right channel and it stop idk what to do :/

**Comment by vic1707** [comment]
If you don't know how to code you can't really do much, I have updated the code twice recently but it doesn't seem to be working due to the last update to discord.
I have to launch the bot myself to do more testing, I just have to find the right identifier for the message bar, but dunno if I'll have time nor when.
Go and take a look at another project linked on the homepage of my repo (since mine is deprecated...)

**Comment by na0sis111** [comment]
hmm okay thank you anyway you're a nice person :)
