### ISSUE TITLE
Malformed URL Issue

### ISSUE THREAD

**Issue by SirInferious** [vic1707/AutoPlay-PokeMeow-Discord#39]
Malformed URL when putting my discord link.
I copied and paste the discord link on discord. Tried removing the https.

It's 01:18:19, working time !
Traceback (most recent call last):
  File "C:\Users\Darren Wong\bot.py", line 39, in <module>
    DRIVER    = CustomDriver(ARGUMENTS)
  File "C:\Users\Darren Wong\Classes\CustomDriver.py", line 72, in __init__
    self.DiscordLogin(self.CHANNEL)
  File "C:\Users\Darren Wong\Classes\CustomDriver.py", line 77, in DiscordLogin
    self.get(CHANNEL)
  File "C:\Users\Darren Wong\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\Darren Wong\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Darren Wong\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidArgumentException: Message: Malformed URL: URL constructor: 'https://discord.com/channels/631808494844248069/8333542410734' is not a valid URL.

**Comment by vic1707** [comment]
Can you send the exact command you used please (hide you credentials!)
Try with the url between " quotes instead of '

**Comment by SirInferious** [comment]
Ok, i have fixed the malformed issue. But once log in. I have the captcha issue that discord is asking for.
Do you still need the code?

**Comment by vic1707** [comment]
Can't do anything for the captcha unfortunately
