### ISSUE TITLE
Cant login to discord

### ISSUE THREAD

**Issue by PieByter** [vic1707/AutoPlay-PokeMeow-Discord#45]
**Describe the bug**
I use English version Firefox but cant login to the discord / autofill the email and password

**Screenshots**
Traceback (most recent call last):
  File "C:\Users\User\3D Objects\AutoPlay-PokeMeow-Discord-main\bot.py", line 46, in <module>
    DRIVER = CustomDriver(ARGUMENTS)
  File "C:\Users\User\3D Objects\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 80, in __init__
    self.DiscordLogin(self.CHANNEL)
  File "C:\Users\User\3D Objects\AutoPlay-PokeMeow-Discord-main\Classes\CustomDriver.py", line 87, in DiscordLogin
    self.find_element_by_name("email").send_keys(self.MAIL)
  File "D:\Compiler Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 496, in find_element_by_name
    return self.find_element(by=By.NAME, value=name)
  File "D:\Compiler Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "D:\Compiler Python\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Compiler Python\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [name="email"]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Additional context**

**Comment by vic1707** [comment]
> This project is not updated anymore and won't ever be, Pokemeow moved to slashcommand and I don't want to rework on that project anymore.

Cf: first line of readme
